# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62cdefc010cb5467deb60b013086aa30c64a07179b8d1af2774236cc0079bd1611c9a5ffff2b8b9b6c74fb5d7431353f82da1d4f13502ec13fc0aecc79d4668c

test:
  secret_key_base: 526568a74b41721b381d9ba5c432081a76b1db8e1b0d2502f6e4ddf935f8b0b37de81c10dfe2e3bd3870f58f393e8b2010c79e5c711bfec9a238108668bb78a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
